# Generated by Django 6.0.4 on 2026-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='tags',
            field=models.CharField(default='General', help_text='Comma separated skills: Python, Array, etc.', max_length=200),
        ),
    ]
