# Generated by Django 6.0.4 on 2026-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_round', '0003_codingproblem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='language',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
