# Generated by Django 6.0.4 on 2026-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='video_recording',
            field=models.FileField(blank=True, null=True, upload_to='interviews/'),
        ),
    ]
