# Generated by Django 6.0.4 on 2026-07-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_resume_nullable_beginner_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
